INSERT INTO program_template_exercises VALUES(9,1,'Bodyweight Squat','3','10-15','Focus on depth and control',1);
INSERT INTO program_template_exercises VALUES(10,1,'Push-up','3','8-12','Modify on knees if needed',2);
INSERT INTO program_template_exercises VALUES(11,1,'Glute Bridge','3','12-15','Squeeze at the top',3);
INSERT INTO program_template_exercises VALUES(12,1,'Dead Bugs','3','10 each side','Keep lower back pressed down',4);
INSERT INTO program_template_exercises VALUES(13,1,'Supermans','3','10-12','Hold for 2 seconds at top',5);
INSERT INTO program_template_exercises VALUES(14,1,'Walking Lunge','2','10 each leg','Keep torso upright',6);
INSERT INTO program_template_exercises VALUES(15,2,'Flat DB Press','3','8-12','Control the descent',1);
INSERT INTO program_template_exercises VALUES(16,2,'Lat Pulldowns','3','10-12','Full stretch at top',2);
INSERT INTO program_template_exercises VALUES(17,2,'Seated DB Press','3','8-10','Press straight up',3);
INSERT INTO program_template_exercises VALUES(18,2,'DB Row','3','10-12 each','Pull elbow back',4);
INSERT INTO program_template_exercises VALUES(19,2,'Biceps Cable Curls','3','12-15','Keep elbows stable',5);
INSERT INTO program_template_exercises VALUES(20,2,'Triceps Pushdown','3','12-15','Full extension',6);
INSERT INTO program_template_exercises VALUES(21,2,'Back Squat','4','8-10','Depth to parallel or below',7);
INSERT INTO program_template_exercises VALUES(22,2,'Romanian Deadlift','3','10-12','Feel hamstring stretch',8);
INSERT INTO program_template_exercises VALUES(23,2,'Leg Press','3','12-15','Full range of motion',9);
INSERT INTO program_template_exercises VALUES(24,2,'Hamstring Curls','3','12-15','Control the negative',10);
INSERT INTO program_template_exercises VALUES(25,2,'Calf Raises','4','15-20','Full stretch and contraction',11);
INSERT INTO program_template_exercises VALUES(26,3,'Flat BB Bench Press','4','6-8','Progressive overload focus',1);
INSERT INTO program_template_exercises VALUES(27,3,'Incline DB Press','3','8-10','Upper chest emphasis',2);
INSERT INTO program_template_exercises VALUES(28,3,'Standing DB Press','3','8-10','Shoulder development',3);
INSERT INTO program_template_exercises VALUES(29,3,'Lateral Raises','3','12-15','Controlled motion',4);
INSERT INTO program_template_exercises VALUES(30,3,'Triceps Pushdown','3','12-15','Lockout at bottom',5);
INSERT INTO program_template_exercises VALUES(31,3,'Deadlift','4','5-8','Maintain neutral spine',6);
INSERT INTO program_template_exercises VALUES(32,3,'Pull-up','3','6-10','Full range of motion',7);
INSERT INTO program_template_exercises VALUES(33,3,'Barbell Row','3','8-10','Pull to lower chest',8);
INSERT INTO program_template_exercises VALUES(34,3,'DB Row','3','10-12 each','Squeeze at top',9);
INSERT INTO program_template_exercises VALUES(35,3,'DB Bicep Curls','3','10-12','No momentum',10);
INSERT INTO program_template_exercises VALUES(36,3,'Back Squat','4','6-8','Below parallel depth',11);
INSERT INTO program_template_exercises VALUES(37,3,'Romanian Deadlift','3','8-10','Hinge at hips',12);
INSERT INTO program_template_exercises VALUES(38,3,'Walking Lunge','3','10 each leg','Long stride',13);
INSERT INTO program_template_exercises VALUES(39,3,'Leg Extensions','3','12-15','Squeeze at top',14);
INSERT INTO program_template_exercises VALUES(40,3,'Hamstring Curls','3','12-15','Control eccentric',15);
INSERT INTO program_template_exercises VALUES(41,4,'Bodyweight Squat','4','15-20','Slow tempo',1);
INSERT INTO program_template_exercises VALUES(42,4,'Push-up','4','10-15','Chest to ground',2);
INSERT INTO program_template_exercises VALUES(43,4,'Split Squat','3','12 each leg','Back knee to ground',3);
INSERT INTO program_template_exercises VALUES(44,4,'Walking Lunge','3','12 each leg','Full range',4);
INSERT INTO program_template_exercises VALUES(45,4,'Dead Bugs','3','12 each side','Core engaged',5);
INSERT INTO program_template_exercises VALUES(46,4,'Glute Bridge','3','15-20','2 second hold at top',6);
INSERT INTO program_template_exercises VALUES(47,4,'Hollow Hold','3','30-45 sec','Lower back down',7);
INSERT INTO program_template_exercises VALUES(48,4,'Supermans','3','15-20','Controlled reps',8);
INSERT INTO program_template_exercises VALUES(49,5,'Back Squat','5','5','Heavy weight, perfect form',1);
INSERT INTO program_template_exercises VALUES(50,5,'Flat BB Bench Press','5','5','2-3 min rest between sets',2);
INSERT INTO program_template_exercises VALUES(51,5,'Deadlift','5','5','Reset each rep',3);
INSERT INTO program_template_exercises VALUES(52,5,'Front Squat','4','6-8','Upright torso',4);
INSERT INTO program_template_exercises VALUES(53,5,'Barbell Row','4','6-8','Explosive pull',5);
INSERT INTO program_template_exercises VALUES(54,5,'Standing BB Press','4','6-8','Full lockout',6);
INSERT INTO program_template_exercises VALUES(55,5,'Romanian Deadlift','3','8-10','Hamstring focus',7);
INSERT INTO program_template_exercises VALUES(56,6,'Flat BB Bench Press','4','8-10','60-90s rest',1);
INSERT INTO program_template_exercises VALUES(57,6,'Incline DB Press','3','10-12','Stretch at bottom',2);
INSERT INTO program_template_exercises VALUES(58,6,'Cable Cross','3','12-15','Chest squeeze',3);
INSERT INTO program_template_exercises VALUES(59,6,'Lat Pulldowns','4','10-12','Wide grip',4);
INSERT INTO program_template_exercises VALUES(60,6,'Seated Cable Row','3','10-12','Retract scapula',5);
INSERT INTO program_template_exercises VALUES(61,6,'DB Row','3','10-12 each','Control movement',6);
INSERT INTO program_template_exercises VALUES(62,6,'Seated DB Press','3','10-12','Shoulder focus',7);
INSERT INTO program_template_exercises VALUES(63,6,'Lateral Raises','3','15-20','Time under tension',8);
INSERT INTO program_template_exercises VALUES(64,6,'DB Bicep Curls','3','12-15','Alternating',9);
INSERT INTO program_template_exercises VALUES(65,6,'Triceps Pushdown','3','12-15','Rope attachment',10);
INSERT INTO program_template_exercises VALUES(66,7,'Back Squat','4','8-10','Progressive weight',1);
INSERT INTO program_template_exercises VALUES(67,7,'Romanian Deadlift','4','10-12','Feel the stretch',2);
INSERT INTO program_template_exercises VALUES(68,7,'Walking Lunge','3','12 each leg','Long stride length',3);
INSERT INTO program_template_exercises VALUES(69,7,'Leg Press','3','12-15','Full depth',4);
INSERT INTO program_template_exercises VALUES(70,7,'Hamstring Curls','3','12-15','Slow eccentric',5);
INSERT INTO program_template_exercises VALUES(71,7,'Leg Extensions','3','12-15','Quad squeeze',6);
INSERT INTO program_template_exercises VALUES(72,7,'Cable Crunch','3','15-20','Flex abs hard',7);
INSERT INTO program_template_exercises VALUES(73,7,'Dead Bugs','3','12 each side','Anti-rotation focus',8);
INSERT INTO program_template_exercises VALUES(74,7,'RKC Plank','3','30-45 sec','Maximum tension',9);
INSERT INTO program_template_exercises VALUES(75,8,'Box Jump','4','5-8','Explosive',1);
INSERT INTO program_template_exercises VALUES(76,8,'Broad Jump','4','5','Maximum distance',2);
INSERT INTO program_template_exercises VALUES(77,8,'Back Squat','4','6-8','Explosive concentric',3);
INSERT INTO program_template_exercises VALUES(78,8,'Romanian Deadlift','3','8-10','Hip power',4);
INSERT INTO program_template_exercises VALUES(79,8,'Sled Push','4','20-30m','Drive through legs',5);
INSERT INTO program_template_exercises VALUES(80,8,'Bear Crawl','3','30 sec','Core stability',6);
INSERT INTO program_template_exercises VALUES(81,8,'Jump Squats','3','8-10','Land softly',7);
INSERT INTO program_template_exercises VALUES(82,8,'Slider Thrusts','3','12-15','Hip extension power',8);
INSERT INTO program_template_exercises VALUES(83,9,'Foam Rolling','1','5 min','All major muscle groups',1);
INSERT INTO program_template_exercises VALUES(84,9,'Diaphragmatic Breathing','3','10 breaths','Deep belly breathing',2);
INSERT INTO program_template_exercises VALUES(85,9,'Childs Pose','3','60 sec','Relax into stretch',3);
INSERT INTO program_template_exercises VALUES(86,9,'Dead Hangs','3','20-30 sec','Shoulder decompression',4);
INSERT INTO program_template_exercises VALUES(87,9,'Glute Bridge','3','15','Activation only',5);
INSERT INTO program_template_exercises VALUES(88,9,'Bodyweight Squat','3','15','Movement quality',6);
INSERT INTO program_template_exercises VALUES(89,9,'Cossack Squat','3','8 each side','Hip mobility',7);
INSERT INTO program_template_exercises VALUES(90,9,'Spiderman Lunge w/ Thoracic Rotation','3','8 each side','Full body mobility',8);
INSERT INTO program_template_exercises VALUES(91,10,'Back Squat','3','8-10','90s rest',1);
INSERT INTO program_template_exercises VALUES(92,10,'Flat BB Bench Press','3','8-10','90s rest',2);
INSERT INTO program_template_exercises VALUES(93,10,'Deadlift','3','8-10','2 min rest',3);
INSERT INTO program_template_exercises VALUES(94,10,'Barbell Row','3','8-10','90s rest',4);
INSERT INTO program_template_exercises VALUES(95,10,'Standing BB Press','3','8-10','90s rest',5);
INSERT INTO program_template_exercises VALUES(96,10,'Romanian Deadlift','3','10-12','60s rest',6);
INSERT INTO program_template_exercises VALUES(97,10,'Pull-up','3','6-10','Assisted if needed',7);
INSERT INTO program_template_exercises VALUES(98,11,'Foam Rolling','1','5 min','All major muscle groups',1);
INSERT INTO program_template_exercises VALUES(99,11,'Diaphragmatic Breathing','3','10 breaths','Deep belly breathing',2);
INSERT INTO program_template_exercises VALUES(100,11,'Childs Pose','3','60 sec','Relax into stretch',3);
INSERT INTO program_template_exercises VALUES(101,11,'Dead Hangs','3','20-30 sec','Shoulder decompression',4);
INSERT INTO program_template_exercises VALUES(102,11,'Glute Bridge','3','15','Activation only',5);
INSERT INTO program_template_exercises VALUES(103,11,'Bodyweight Squat','3','15','Movement quality',6);
INSERT INTO program_template_exercises VALUES(104,11,'Cossack Squat','3','8 each side','Hip mobility',7);
INSERT INTO program_template_exercises VALUES(105,11,'Spiderman Lunge w/ Thoracic Rotation','3','8 each side','Full body mobility',8);
INSERT INTO program_template_exercises VALUES(106,12,'Back Squat','3','8-10','90s rest',1);
INSERT INTO program_template_exercises VALUES(107,12,'Flat BB Bench Press','3','8-10','90s rest',2);
INSERT INTO program_template_exercises VALUES(108,12,'Deadlift','3','8-10','2 min rest',3);
INSERT INTO program_template_exercises VALUES(109,12,'Barbell Row','3','8-10','90s rest',4);
INSERT INTO program_template_exercises VALUES(110,12,'Standing BB Press','3','8-10','90s rest',5);
INSERT INTO program_template_exercises VALUES(111,12,'Romanian Deadlift','3','10-12','60s rest',6);
INSERT INTO program_template_exercises VALUES(112,12,'Pull-up','3','6-10','Assisted if needed',7);
